# generate-media-list.ps1
# Scans the images/ and videos/ folders and generates media-list.js
# Run this script whenever you add or remove files from those folders.

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$imagesDir = Join-Path $scriptDir "images"
$videosDir = Join-Path $scriptDir "videos"
$outputFile = Join-Path $scriptDir "media-list.js"

$entries = @()

# Scan images folder
if (Test-Path $imagesDir) {
    $imageFiles = Get-ChildItem -Path $imagesDir -File | Where-Object {
        $_.Extension -match '\.(jpg|jpeg|png|gif|webp|bmp|svg)$'
    } | Sort-Object Name
    foreach ($f in $imageFiles) {
        $entries += "    { type: 'image', file: '$($f.Name)' }"
    }
}

# Scan videos folder
if (Test-Path $videosDir) {
    $videoFiles = Get-ChildItem -Path $videosDir -File | Where-Object {
        $_.Extension -match '\.(mp4|webm|mov|avi|mkv)$'
    } | Sort-Object Name
    foreach ($f in $videoFiles) {
        $entries += "    { type: 'video', file: '$($f.Name)' }"
    }
}

# Build the JS file
$js = @"
// Auto-generated by generate-media-list.ps1
// DO NOT EDIT — run the script again to regenerate.
// Images found: $((($entries | Where-Object { $_ -match "image" }).Count))
// Videos found: $((($entries | Where-Object { $_ -match "video" }).Count))
var MEDIA_LIST = [
$($entries -join ",`n")
];
"@

Set-Content -Path $outputFile -Value $js -Encoding UTF8
Write-Host "Generated $outputFile with $($entries.Count) media items."
