// Auto-generated by generate-media-list.ps1
// DO NOT EDIT â€” run the script again to regenerate.
// Images found: 3
// Videos found: 2
var MEDIA_LIST = [
    { type: 'image', file: 'eid1.jpeg' },
    { type: 'image', file: 'eid3.jpeg' },
    { type: 'image', file: 'roseOnHead.jpeg' },
    // { type: 'video', file: 'reactionWhileReading.mp4' },
    { type: 'video', file: 'reaction.mp4' },
    { type: 'video', file: 'sheWithRoseOnHead.mp4' }
];
